<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PacaGroup.Ecommerce.Infraestructura.Data\PacaGroup.Ecommerce.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\PacaGroup.Ecommerce.Infrastructure.Interface\PacaGroup.Ecommerce.Infrastructure.Interface.csproj" />
    <ProjectReference Include="..\PacaGroup.Ecommerce.Transversal.Common\PacaGroup.Ecommerce.Transversal.Common.csproj" />
  </ItemGroup>

</Project>
